# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:18-alpine

# Create app directory
WORKDIR /app

# install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# Copy source
COPY . .

# Build the project
RUN npm run build

# Default to stdio transport
CMD ["node", "build/index.js", "--transport", "stdio"]
